/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import java.io.IOException;
import static java.lang.Compiler.command;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import other.TimeCalculator;

/**
 *
 * @author DinukaMedis
 */
public class AdminMain extends javax.swing.JFrame {

    ManageCoursePanel manageCoursePanel;
    ManageInstructorPanel manageInstructorPanel;
    ManageLecturerPanel manageLecturerPanel;
    ManagePaymentsPanel managePaymentsPanel;
    ManageSubjectPanel manageSubjectPanel;
    MainStudentPanel mainStudentPanel;
    ManageStudentPanel manageStudentPanel;
    ManageFacultyPanel manageFacultyPanel;
    ManageAdminPanel manageAdminPanel;
    ResultsPanel resultsPanel;
    /**
     * Creates new form AdminMain
     */
    public AdminMain(String adminName) {
        initComponents();
        this.adminName.setText(adminName);
       // new AdminLogin(this, true).setVisible(true);
        setTime();
        checkRegistration();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainWindow = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        courseBtn = new javax.swing.JButton();
        instructorBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        subjectBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        lectBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        manageStudentBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        facutyBtn = new javax.swing.JButton();
        newAdminBtn = new javax.swing.JLabel();
        resultBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        mainWindow.setBackground(new java.awt.Color(255, 255, 255));
        mainWindow.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 3, 82)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.gif"))); // NOI18N
        mainWindow.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(mainWindow);
        mainWindow.setBounds(220, 70, 1110, 620);

        courseBtn.setBackground(new java.awt.Color(51, 255, 255));
        courseBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courseBtn.setText("Course");
        courseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(courseBtn);
        courseBtn.setBounds(20, 360, 180, 40);

        instructorBtn.setBackground(new java.awt.Color(51, 255, 255));
        instructorBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        instructorBtn.setText("Instructor");
        instructorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(instructorBtn);
        instructorBtn.setBounds(20, 240, 180, 40);

        paymentBtn.setBackground(new java.awt.Color(51, 255, 255));
        paymentBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        paymentBtn.setText("Payments");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentBtn);
        paymentBtn.setBounds(20, 300, 180, 40);

        subjectBtn.setBackground(new java.awt.Color(51, 255, 255));
        subjectBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        subjectBtn.setText("Subjects");
        subjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectBtnActionPerformed(evt);
            }
        });
        jPanel1.add(subjectBtn);
        subjectBtn.setBounds(20, 480, 180, 40);

        registerBtn.setBackground(new java.awt.Color(51, 255, 255));
        registerBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 0, 0));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn);
        registerBtn.setBounds(20, 120, 180, 40);

        lectBtn.setBackground(new java.awt.Color(51, 255, 255));
        lectBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lectBtn.setText("Lecturer");
        lectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectBtnActionPerformed(evt);
            }
        });
        jPanel1.add(lectBtn);
        lectBtn.setBounds(20, 540, 180, 40);

        jLabel2.setText("Designed by Dinuka Kasun Medis | dinuka.kasunds@gmail.com | 0717275722");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(960, 700, 370, 14);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1270, 10, 60, 60);

        adminName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adminName.setForeground(new java.awt.Color(255, 255, 255));
        adminName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminName.setText("Admin");
        jPanel1.add(adminName);
        adminName.setBounds(1070, 10, 200, 30);

        timeLbl.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(255, 255, 255));
        timeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLbl.setText("14:52:32");
        jPanel1.add(timeLbl);
        timeLbl.setBounds(1120, 40, 100, 30);

        manageStudentBtn.setBackground(new java.awt.Color(51, 255, 255));
        manageStudentBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        manageStudentBtn.setText("Manage Student");
        manageStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageStudentBtn);
        manageStudentBtn.setBounds(20, 180, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NSBMlogo_2.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 210, 89);

        facutyBtn.setBackground(new java.awt.Color(51, 255, 255));
        facutyBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        facutyBtn.setText("Faculty");
        facutyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facutyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(facutyBtn);
        facutyBtn.setBounds(20, 420, 180, 40);

        newAdminBtn.setBackground(new java.awt.Color(255, 0, 0));
        newAdminBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newAdminBtn.setForeground(new java.awt.Color(255, 51, 51));
        newAdminBtn.setText("Manage Admin");
        newAdminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newAdminBtnMouseClicked(evt);
            }
        });
        jPanel1.add(newAdminBtn);
        newAdminBtn.setBounds(10, 710, 100, 15);

        resultBtn.setBackground(new java.awt.Color(51, 255, 255));
        resultBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resultBtn.setText("Results");
        resultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resultBtn);
        resultBtn.setBounds(20, 610, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backGround1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBtnActionPerformed
        manageCoursePanel = new ManageCoursePanel();
        mainWindow.removeAll();
        mainWindow.add(manageCoursePanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageCoursePanel.setVisible(true);
    }//GEN-LAST:event_courseBtnActionPerformed

    private void instructorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorBtnActionPerformed
        manageInstructorPanel = new ManageInstructorPanel();
        mainWindow.removeAll();
        mainWindow.add(manageInstructorPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageInstructorPanel.setVisible(true);
    }//GEN-LAST:event_instructorBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        managePaymentsPanel = new ManagePaymentsPanel();
        mainWindow.removeAll();
        mainWindow.add(managePaymentsPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        managePaymentsPanel.setVisible(true);
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void subjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectBtnActionPerformed
        manageSubjectPanel = new ManageSubjectPanel();
        mainWindow.removeAll();
        mainWindow.add(manageSubjectPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageSubjectPanel.setVisible(true);
    }//GEN-LAST:event_subjectBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        mainStudentPanel = new MainStudentPanel(this);
        mainWindow.removeAll();
        mainWindow.add(mainStudentPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        mainStudentPanel.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void lectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectBtnActionPerformed
        manageLecturerPanel = new ManageLecturerPanel();
        mainWindow.removeAll();
        mainWindow.add(manageLecturerPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageLecturerPanel.setVisible(true);
    }//GEN-LAST:event_lectBtnActionPerformed

    private void manageStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentBtnActionPerformed
        manageStudentPanel = new ManageStudentPanel(this);
        mainWindow.removeAll();
        mainWindow.add(manageStudentPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageStudentPanel.setVisible(true);
    }//GEN-LAST:event_manageStudentBtnActionPerformed

    private void newAdminBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newAdminBtnMouseClicked
        manageAdminPanel = new ManageAdminPanel();
        mainWindow.removeAll();
        mainWindow.add(manageAdminPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageAdminPanel.setVisible(true);
    }//GEN-LAST:event_newAdminBtnMouseClicked

    private void resultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBtnActionPerformed
        resultsPanel = new ResultsPanel(this);
        mainWindow.removeAll();
        mainWindow.add(resultsPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        resultsPanel.setVisible(true);
    }//GEN-LAST:event_resultBtnActionPerformed

    private void facutyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facutyBtnActionPerformed
        manageFacultyPanel = new ManageFacultyPanel();
        mainWindow.removeAll();
        mainWindow.add(manageFacultyPanel);
        mainWindow.repaint();
        mainWindow.revalidate();
        manageFacultyPanel.setVisible(true);
    }//GEN-LAST:event_facutyBtnActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminMain().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminName;
    private javax.swing.JButton courseBtn;
    private javax.swing.JButton facutyBtn;
    private javax.swing.JButton instructorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lectBtn;
    public javax.swing.JPanel mainWindow;
    private javax.swing.JButton manageStudentBtn;
    private javax.swing.JLabel newAdminBtn;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resultBtn;
    private javax.swing.JButton subjectBtn;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables

    private void setTime() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Date date = new Date();
                        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh:mm:ss");
                        SimpleDateFormat simpleDateFormat2 = new SimpleDateFormat("yyyy MMMM,dd");
                        timeLbl.setText(simpleDateFormat.format(date));
                        //dateLbl.setText(simpleDateFormat2.format(date));
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }
    
    private void checkRegistration(){
        if (!TimeCalculator.canIntake()) {
            registerBtn.setText("Reg. Closed");
            registerBtn.setEnabled(false);
        }
    }
}
