/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DinukaMedis
 */
public class ExameSelectorPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form SubjectNamePanel
     * @param subjectName
     * @param price
     */
    public ExameSelectorPanel(String examId, String examName,String date) {
        initComponents();
        examIdTxt.setText(examId);
        examNameTxt.setText(examName);
        dateTxt.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        subjectNameTxt1 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        examNameTxt = new javax.swing.JLabel();
        examIdTxt = new javax.swing.JLabel();
        openBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subjectNameTxt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        subjectNameTxt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excelIcon.png"))); // NOI18N
        jPanel2.add(subjectNameTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        dateTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateTxt.setText("2018-02-02");
        jPanel2.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 0, 150, 40));

        examNameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        examNameTxt.setText("exam Name");
        jPanel2.add(examNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 230, 40));

        examIdTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        examIdTxt.setText("e0001");
        jPanel2.add(examIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 230, 40));

        openBtn.setBackground(new java.awt.Color(51, 255, 255));
        openBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        openBtn.setText("Open");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        jPanel2.add(openBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 4, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        try {
            String path="src\\examResults\\e0001_s0001_2018-06-20.xls";
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+path);
//            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\DinukaMedis\\Documents\\test.xlsx");
        } catch (IOException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTxt;
    private javax.swing.JLabel examIdTxt;
    private javax.swing.JLabel examNameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton openBtn;
    private javax.swing.JLabel subjectNameTxt1;
    // End of variables declaration//GEN-END:variables
}
