/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

/**
 *
 * @author DinukaMedis
 */
public class MainStudentPanel extends javax.swing.JPanel {

    private final AdminMain adminMain;
    private RegisterPostGraduateStudentPanel registerPostGraduateStudentPanel;
    private RegisterUnderGraduateStudentPanel registerUnderGraduateStudentPanel;
    
    /**
     * Creates new form MainStudentPanel
     * @param adminMain
     */
    public MainStudentPanel(AdminMain adminMain) {
        initComponents();
        this.adminMain = adminMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        postGraduateBtn = new javax.swing.JButton();
        underGraduateBtn = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postGraduateBtn.setBackground(new java.awt.Color(51, 255, 255));
        postGraduateBtn.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        postGraduateBtn.setText("PostGraduate Student");
        postGraduateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postGraduateBtnActionPerformed(evt);
            }
        });
        backPanel.add(postGraduateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 520, 120));

        underGraduateBtn.setBackground(new java.awt.Color(51, 255, 255));
        underGraduateBtn.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        underGraduateBtn.setText("UnderGraduate Student");
        underGraduateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underGraduateBtnActionPerformed(evt);
            }
        });
        backPanel.add(underGraduateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 520, 120));

        logoLbl.setFont(new java.awt.Font("Tekton Pro", 3, 82)); // NOI18N
        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nsbm_logo.gif"))); // NOI18N
        backPanel.add(logoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 220, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*Load postGaduate panel © DK*/
    private void postGraduateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postGraduateBtnActionPerformed
        registerPostGraduateStudentPanel = new RegisterPostGraduateStudentPanel();
        adminMain.mainWindow.removeAll();
        adminMain.mainWindow.add(registerPostGraduateStudentPanel);
        adminMain.mainWindow.repaint();
        adminMain.mainWindow.revalidate();
        registerPostGraduateStudentPanel.setVisible(true);
    }//GEN-LAST:event_postGraduateBtnActionPerformed

    /*Load underGaduate panel © DK*/
    private void underGraduateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underGraduateBtnActionPerformed
        registerUnderGraduateStudentPanel = new RegisterUnderGraduateStudentPanel();
        adminMain.mainWindow.removeAll();
        adminMain.mainWindow.add(registerUnderGraduateStudentPanel);
        adminMain.mainWindow.repaint();
        adminMain.mainWindow.revalidate();
        registerUnderGraduateStudentPanel.setVisible(true);
    }//GEN-LAST:event_underGraduateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JButton postGraduateBtn;
    private javax.swing.JButton underGraduateBtn;
    // End of variables declaration//GEN-END:variables
}
