/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import controller.FacultyController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Faculty;
import other.ComboSearch;
import other.IDGenerator;

/**
 *
 * @author DinukaMedis
 */
public class ManageFacultyPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFacultyPanel
     */
    public ManageFacultyPanel() {
        initComponents();
        fillFacultyCombo();
        facultyIdCombo.setVisible(true);
        facultyIdTxt.setVisible(false);
        newCourseBtn.setVisible(true);
        addBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        facultyIdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        deeteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        updateBtn1 = new javax.swing.JButton();
        facultyIdCombo = new javax.swing.JComboBox<>();
        newCourseBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Faculty ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 130, 30));

        facultyIdTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        facultyIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyIdTxtActionPerformed(evt);
            }
        });
        facultyIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                facultyIdTxtKeyReleased(evt);
            }
        });
        jPanel1.add(facultyIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, 30));

        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
        });
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 370, -1));

        deeteBtn.setBackground(new java.awt.Color(51, 255, 255));
        deeteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deeteBtn.setText("DELETE");
        deeteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deeteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deeteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 200, 40));

        addBtn.setBackground(new java.awt.Color(51, 255, 255));
        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 200, 40));

        updateBtn1.setBackground(new java.awt.Color(51, 255, 255));
        updateBtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateBtn1.setText("UPDATE ");
        updateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 200, 40));

        facultyIdCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        facultyIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facultyIdComboItemStateChanged(evt);
            }
        });
        jPanel1.add(facultyIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, -1));

        newCourseBtn.setBackground(new java.awt.Color(51, 255, 255));
        newCourseBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newCourseBtn.setText("NEW FACULTY");
        newCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(newCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void facultyIdTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyIdTxtKeyReleased

    }//GEN-LAST:event_facultyIdTxtKeyReleased

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtKeyReleased

    private void deeteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deeteBtnActionPerformed
        try {
            String facultyId = facultyIdCombo.getSelectedItem().toString();
            int isDeleted=FacultyController.deleteFaculty(facultyId);
            if (isDeleted>0) {
                JOptionPane.showMessageDialog(this, "Faculty Deleted success...");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "Somthing wrong...");
                refresh();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageFacultyPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deeteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            String faculty = facultyIdTxt.getText();
            String name = nameTxt.getText();
            Faculty faculty1=new Faculty(faculty, name);
            int isAdded=FacultyController.addFaculty(faculty1);
            if (isAdded>0) {
                JOptionPane.showMessageDialog(this, "Faculty added success...");
                facultyIdCombo.setVisible(true);
                facultyIdTxt.setVisible(false);
                newCourseBtn.setVisible(true);
                addBtn.setVisible(false);
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "Somthing wrong...");
                facultyIdCombo.setVisible(true);
                facultyIdTxt.setVisible(false);
                newCourseBtn.setVisible(true);
                addBtn.setVisible(false);
                refresh();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageFacultyPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn1ActionPerformed
        try {
            String faculty = facultyIdCombo.getSelectedItem().toString();
            String name = nameTxt.getText();
            Faculty faculty1=new Faculty(faculty, name);
            int isUpdated=FacultyController.updateFaculty(faculty1);
            if (isUpdated>0) {
                JOptionPane.showMessageDialog(this, "Faculty Updated success...");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "Somthing wrong...");
                refresh();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageFacultyPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageFacultyPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBtn1ActionPerformed

    private void facultyIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facultyIdComboItemStateChanged
        try {
            if (facultyIdCombo.getSelectedItem()!=null) {
                String facultyId = facultyIdCombo.getSelectedItem().toString();
                Faculty faculty=FacultyController.searchFacultyId(facultyId);
                if (faculty!=null) {
                    nameTxt.setText(faculty.getName());
                }else{
                    JOptionPane.showMessageDialog(this, "Somthing wrong...");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageCoursePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facultyIdComboItemStateChanged

    private void newCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseBtnActionPerformed
        try {
            facultyIdCombo.setVisible(false);
            facultyIdTxt.setVisible(true);
            newCourseBtn.setVisible(false);
            addBtn.setVisible(true);
            String newId = IDGenerator.getNewId("faculty", "facultyId", "f");
            facultyIdTxt.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageAdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newCourseBtnActionPerformed

    private void facultyIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyIdTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deeteBtn;
    private javax.swing.JComboBox<String> facultyIdCombo;
    private javax.swing.JTextField facultyIdTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton newCourseBtn;
    private javax.swing.JButton updateBtn1;
    // End of variables declaration//GEN-END:variables

     private void fillFacultyCombo(){
        try {
            ArrayList<Faculty> faculties=FacultyController.getAllFaculty();
            for (Faculty faculty : faculties) {
                facultyIdCombo.addItem(faculty.getFacultyId());
            }
            new ComboSearch().setSearchableCombo(facultyIdCombo, true, "No Faculty found");
            //new ComboSearch().setSearchableCombo(student_idCOmbo, true, "No Student found");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    private void refresh(){
        facultyIdCombo.removeAllItems();
        fillFacultyCombo();
    }
}
