/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import controller.BscSubjectController;
import controller.CourseController;
import controller.FacultyController;
import controller.MscSubjectController;
import controller.PostGraduateStudentController;
import controller.SubjectController;
import controller.UnderGraduateStudentController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.BscSubject;
import model.GetBscSubjects;
import model.GetMscSubjects;
import model.MscSubjects;
import model.PostGraduateStudent;
import model.Subject;
import model.UnderGraduateStudent;
import other.ComboSearch;
import other.TimeCalculator;

/**
 *
 * @author DinukaMedis
 */
public class ManageStudentPanel extends javax.swing.JPanel {
    
    SelectSubjectPanel_old selectSubjectPanel;
    AdminMain adminMain;
    static String unAdmissionNo="";
    static String postAdmissionNo="";
    static ArrayList<String > unSem1SubjectCodes=new ArrayList<>();
    static ArrayList<String > unSem2SubjectCodes=new ArrayList<>();
    static ArrayList<String > psSem1SubjectCodes=new ArrayList<>();
    static ArrayList<String > psSem2SubjectCodes=new ArrayList<>();
    /**
     * Creates new form TabPanelTest
     */
    public ManageStudentPanel(AdminMain adminMain) {
        initComponents();
        fillUnderGraduatesAdmissionNoCombo();
        fillPostGraduatesAdmissionNoCombo();
        loadCompulsarrySubjects();
        loadPostGraduteSubjects();
        loadUnderGraduteSubjects();
        this.adminMain=adminMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        picFrame = new javax.swing.JLabel();
        changePicBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        unCourseTxt = new javax.swing.JTextField();
        unEmailTxt = new javax.swing.JTextField();
        unAddmissionDateTxt = new javax.swing.JTextField();
        unNameTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        unYearTxt = new javax.swing.JTextField();
        underGadmissionNoCombo = new javax.swing.JComboBox<>();
        unFacultyTxt = new javax.swing.JTextField();
        underGraSaveBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        sem1TotalTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        unSem1ManageSubjectBtn = new javax.swing.JButton();
        bscSem1Payment = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        unSem1SubjectPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        sem2TotalTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        bscSem2Payment = new javax.swing.JButton();
        unSem2ManageSubjectBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        unSem2SubjectPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        postPicFrame = new javax.swing.JLabel();
        changePicBtn1 = new javax.swing.JButton();
        postGraSaveBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        postFacultyTxt = new javax.swing.JTextField();
        postEmailTxt = new javax.swing.JTextField();
        postAddmissionDateTxt = new javax.swing.JTextField();
        postNameTxt = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        postYearTxt = new javax.swing.JTextField();
        postGadmissionNoCombo = new javax.swing.JComboBox<>();
        postCourseTxt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        sem1TotalTxt1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        mscSem1Payment = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        postSem1SubjectPanel = new javax.swing.JPanel();
        postSem1ManageSubjectBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        sem2TotalTxt1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        mscSem2Payment = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        postSem2SubjectPanel = new javax.swing.JPanel();
        postSem2ManageSubjectBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePics/dpSample.png"))); // NOI18N
        picFrame.setText("jLabel1");
        picFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(picFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 150));

        changePicBtn.setText("Change");
        jPanel2.add(changePicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Course :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 90, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Faculty :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Admission No :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Admission Date :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("E mail :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        unCourseTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(unCourseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 260, -1));

        unEmailTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(unEmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 310, -1));

        unAddmissionDateTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(unAddmissionDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 200, -1));

        unNameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(unNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 310, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Year :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        unYearTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        unYearTxt.setText("1");
        jPanel3.add(unYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        underGadmissionNoCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        underGadmissionNoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                underGadmissionNoComboItemStateChanged(evt);
            }
        });
        jPanel3.add(underGadmissionNoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 260, -1));

        unFacultyTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(unFacultyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 260, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 910, 200));

        underGraSaveBtn.setBackground(new java.awt.Color(51, 255, 255));
        underGraSaveBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        underGraSaveBtn.setText("SAVE");
        underGraSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underGraSaveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(underGraSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 190, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem1TotalTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel4.add(sem1TotalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 51));
        jLabel25.setText("PAID");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Total :");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        unSem1ManageSubjectBtn.setBackground(new java.awt.Color(51, 255, 255));
        unSem1ManageSubjectBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        unSem1ManageSubjectBtn.setText("Manage Subjects");
        unSem1ManageSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unSem1ManageSubjectBtnActionPerformed(evt);
            }
        });
        jPanel4.add(unSem1ManageSubjectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 30));

        bscSem1Payment.setBackground(new java.awt.Color(51, 255, 255));
        bscSem1Payment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bscSem1Payment.setText("Make Payment");
        bscSem1Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscSem1PaymentActionPerformed(evt);
            }
        });
        jPanel4.add(bscSem1Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, 30));

        unSem1SubjectPanel.setLayout(new javax.swing.BoxLayout(unSem1SubjectPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(unSem1SubjectPanel);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 150));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 440, 280));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem2TotalTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel8.add(sem2TotalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 51, 0));
        jLabel27.setText("NOT PAID");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 30));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel37.setText("Total :");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        bscSem2Payment.setBackground(new java.awt.Color(51, 255, 255));
        bscSem2Payment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bscSem2Payment.setText("Make Payment");
        bscSem2Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscSem2PaymentActionPerformed(evt);
            }
        });
        jPanel8.add(bscSem2Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, 30));

        unSem2ManageSubjectBtn.setBackground(new java.awt.Color(51, 255, 255));
        unSem2ManageSubjectBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        unSem2ManageSubjectBtn.setText("Manage Subjects");
        unSem2ManageSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unSem2ManageSubjectBtnActionPerformed(evt);
            }
        });
        jPanel8.add(unSem2ManageSubjectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 30));

        unSem2SubjectPanel.setLayout(new javax.swing.BoxLayout(unSem2SubjectPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(unSem2SubjectPanel);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 150));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 440, 280));

        jTabbedPane1.addTab("Undergaraduate Student", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postPicFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePics/dpSample.png"))); // NOI18N
        postPicFrame.setText("jLabel1");
        postPicFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(postPicFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 150));

        changePicBtn1.setText("Change");
        changePicBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePicBtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(changePicBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        postGraSaveBtn.setBackground(new java.awt.Color(51, 255, 255));
        postGraSaveBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        postGraSaveBtn.setText("SAVE");
        postGraSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postGraSaveBtnActionPerformed(evt);
            }
        });
        jPanel5.add(postGraSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 190, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel38.setText("Course :");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 90, 30));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel39.setText("Faculty :");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Admission No :");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel40.setText("Admission Date :");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 130, 30));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel41.setText("Name :");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel42.setText("E mail :");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        postFacultyTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel9.add(postFacultyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 200, -1));

        postEmailTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel9.add(postEmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 310, -1));

        postAddmissionDateTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel9.add(postAddmissionDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 200, -1));

        postNameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel9.add(postNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 310, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel43.setText("Year :");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        postYearTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel9.add(postYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        postGadmissionNoCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        postGadmissionNoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                postGadmissionNoComboItemStateChanged(evt);
            }
        });
        jPanel9.add(postGadmissionNoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 260, -1));

        postCourseTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel9.add(postCourseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 260, -1));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 910, 200));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem1TotalTxt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel10.add(sem1TotalTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 153, 51));
        jLabel48.setText("PAID");
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 30));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel49.setText("Total :");
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        mscSem1Payment.setBackground(new java.awt.Color(51, 255, 255));
        mscSem1Payment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mscSem1Payment.setText("Make Payment");
        mscSem1Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mscSem1PaymentActionPerformed(evt);
            }
        });
        jPanel10.add(mscSem1Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, 30));

        postSem1SubjectPanel.setLayout(new javax.swing.BoxLayout(postSem1SubjectPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane4.setViewportView(postSem1SubjectPanel);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 150));

        postSem1ManageSubjectBtn.setBackground(new java.awt.Color(51, 255, 255));
        postSem1ManageSubjectBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        postSem1ManageSubjectBtn.setText("Manage Subjects");
        postSem1ManageSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postSem1ManageSubjectBtnActionPerformed(evt);
            }
        });
        jPanel10.add(postSem1ManageSubjectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 30));

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 440, 280));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem2TotalTxt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel11.add(sem2TotalTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 51, 0));
        jLabel50.setText("NOT PAID");
        jPanel11.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 30));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel55.setText("Total :");
        jPanel11.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        mscSem2Payment.setBackground(new java.awt.Color(51, 255, 255));
        mscSem2Payment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mscSem2Payment.setText("Make Payment");
        mscSem2Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mscSem2PaymentActionPerformed(evt);
            }
        });
        jPanel11.add(mscSem2Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, 30));

        postSem2SubjectPanel.setLayout(new javax.swing.BoxLayout(postSem2SubjectPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane5.setViewportView(postSem2SubjectPanel);

        jPanel11.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 150));

        postSem2ManageSubjectBtn.setBackground(new java.awt.Color(51, 255, 255));
        postSem2ManageSubjectBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        postSem2ManageSubjectBtn.setText("Manage Subjects");
        postSem2ManageSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postSem2ManageSubjectBtnActionPerformed(evt);
            }
        });
        jPanel11.add(postSem2ManageSubjectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 30));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 440, 280));

        jTabbedPane1.addTab("PostGraduate Student", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 620));
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void underGraSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underGraSaveBtnActionPerformed
        
    }//GEN-LAST:event_underGraSaveBtnActionPerformed

    private void postGraSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postGraSaveBtnActionPerformed
        
    }//GEN-LAST:event_postGraSaveBtnActionPerformed

    private void underGadmissionNoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_underGadmissionNoComboItemStateChanged
        try {
            if (underGadmissionNoCombo.getSelectedItem()!=null) {
                unAdmissionNo= underGadmissionNoCombo.getSelectedItem().toString();
                UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                        searchUnderGraduateStudent(unAdmissionNo);
                if (underGraduateStudent!=null) {
                    unNameTxt.setText(underGraduateStudent.getName());
                    picFrame.setIcon(new javax.swing.ImageIcon(getClass().
                            getResource("/images/profilePics/"+unAdmissionNo+".png")));
                    unEmailTxt.setText(underGraduateStudent.getEmail());
                    //unYearTxt.setText(underGraduateStudent.getYear());
                    unAddmissionDateTxt.setText(underGraduateStudent.getAddmissionDate());
                    unFacultyTxt.setText(FacultyController.searchFacultyId(underGraduateStudent.getFacultyId()).getName());
                    unCourseTxt.setText(CourseController.searchCourseId(underGraduateStudent.getCourseId()).getName());
                    //loadUnderGraduteSubjects();
                    loadUnderGraduteSubjects();
                }else{
                    JOptionPane.showMessageDialog(this, "Somthing wrong...");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_underGadmissionNoComboItemStateChanged

    private void postGadmissionNoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_postGadmissionNoComboItemStateChanged
        try {
            if (postGadmissionNoCombo.getSelectedItem()!=null) {
                postAdmissionNo= postGadmissionNoCombo.getSelectedItem().toString();
                PostGraduateStudent postGraduateStudent=PostGraduateStudentController.
                        searchPostGraduateStudent(postAdmissionNo);
                if (postGraduateStudent!=null) {
                    postNameTxt.setText(postGraduateStudent.getName());
                    postPicFrame.setIcon(new javax.swing.ImageIcon(getClass().
                            getResource("/images/profilePics/"+postAdmissionNo+".png")));
                    postEmailTxt.setText(postGraduateStudent.getEmail());
                    //unYearTxt.setText(underGraduateStudent.getYear());
                    postAddmissionDateTxt.setText(postGraduateStudent.getAddmissionDate());
                    postFacultyTxt.setText(FacultyController.searchFacultyId(postGraduateStudent.getFacultyId()).getName());
                    postCourseTxt.setText(CourseController.searchCourseId(postGraduateStudent.getCourseId()).getName());
                    loadPostGraduteSubjects();
                }else{
                    JOptionPane.showMessageDialog(this, "Somthing wrong...");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_postGadmissionNoComboItemStateChanged

    private void unSem1ManageSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unSem1ManageSubjectBtnActionPerformed
        try {
            String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                    searchUnderGraduateStudent(underGraduateStudentId);
            selectSubjectPanel=new SelectSubjectPanel_old(this.adminMain, true, underGraduateStudent.getCourseId(),
                    Integer.parseInt(unYearTxt.getText()), 1,"BSC");
            selectSubjectPanel.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_unSem1ManageSubjectBtnActionPerformed

    private void mscSem1PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mscSem1PaymentActionPerformed
        try {
            //String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                    searchUnderGraduateStudent(unAdmissionNo);
            MakePayment payment=new MakePayment("MSC",unAdmissionNo,underGraduateStudent.getName(),underGraduateStudent.getEmail()
                    ,underGraduateStudent.getPhoneNo(),psSem1SubjectCodes);
            payment.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mscSem1PaymentActionPerformed

    private void bscSem1PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscSem1PaymentActionPerformed
        try {
            String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                    searchUnderGraduateStudent(underGraduateStudentId);
            MakePayment payment=new MakePayment("BSC",unAdmissionNo,underGraduateStudent.getName(),underGraduateStudent.getEmail()
                    ,underGraduateStudent.getPhoneNo(),unSem1SubjectCodes);
            payment.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bscSem1PaymentActionPerformed

    private void bscSem2PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscSem2PaymentActionPerformed
        try {
            String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                    searchUnderGraduateStudent(underGraduateStudentId);
            MakePayment payment=new MakePayment("BSC",unAdmissionNo,underGraduateStudent.getName(),underGraduateStudent.getEmail()
                    ,underGraduateStudent.getPhoneNo(),unSem2SubjectCodes);
            payment.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bscSem2PaymentActionPerformed

    private void mscSem2PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mscSem2PaymentActionPerformed
        try {
            String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                    searchUnderGraduateStudent(underGraduateStudentId);
            MakePayment payment=new MakePayment("MSC",unAdmissionNo,underGraduateStudent.getName(),underGraduateStudent.getEmail()
                    ,underGraduateStudent.getPhoneNo(),psSem1SubjectCodes);
            payment.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mscSem2PaymentActionPerformed

    private void unSem2ManageSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unSem2ManageSubjectBtnActionPerformed
        try {
            String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.
                    searchUnderGraduateStudent(underGraduateStudentId);
            selectSubjectPanel=new SelectSubjectPanel_old(this.adminMain, true, underGraduateStudent.getCourseId(),
                    Integer.parseInt(unYearTxt.getText()), 2,"BSC");
            selectSubjectPanel.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_unSem2ManageSubjectBtnActionPerformed

    private void postSem1ManageSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postSem1ManageSubjectBtnActionPerformed
        try {
            String postGraduateStudentId = postGadmissionNoCombo.getSelectedItem().toString();
            PostGraduateStudent postGraduateStudent=PostGraduateStudentController.
                    searchPostGraduateStudent(postGraduateStudentId);
            selectSubjectPanel=new SelectSubjectPanel_old(this.adminMain, true, postGraduateStudent.getCourseId(),
                    Integer.parseInt(unYearTxt.getText()), 1,"MSC");
            selectSubjectPanel.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_postSem1ManageSubjectBtnActionPerformed

    private void postSem2ManageSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postSem2ManageSubjectBtnActionPerformed
        try {
            String postGraduateStudentId = postGadmissionNoCombo.getSelectedItem().toString();
            PostGraduateStudent postGraduateStudent=PostGraduateStudentController.
                    searchPostGraduateStudent(postGraduateStudentId);
            selectSubjectPanel=new SelectSubjectPanel_old(this.adminMain, true, postGraduateStudent.getCourseId(),
                    Integer.parseInt(unYearTxt.getText()), 2,"MSC");
            selectSubjectPanel.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_postSem2ManageSubjectBtnActionPerformed

    private void changePicBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePicBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changePicBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bscSem1Payment;
    private javax.swing.JButton bscSem2Payment;
    private javax.swing.JButton changePicBtn;
    private javax.swing.JButton changePicBtn1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton mscSem1Payment;
    private javax.swing.JButton mscSem2Payment;
    private javax.swing.JLabel picFrame;
    private javax.swing.JTextField postAddmissionDateTxt;
    private static javax.swing.JTextField postCourseTxt;
    private javax.swing.JTextField postEmailTxt;
    private javax.swing.JTextField postFacultyTxt;
    private static javax.swing.JComboBox<String> postGadmissionNoCombo;
    private javax.swing.JButton postGraSaveBtn;
    private javax.swing.JTextField postNameTxt;
    private javax.swing.JLabel postPicFrame;
    private javax.swing.JButton postSem1ManageSubjectBtn;
    private static javax.swing.JPanel postSem1SubjectPanel;
    private javax.swing.JButton postSem2ManageSubjectBtn;
    private static javax.swing.JPanel postSem2SubjectPanel;
    private javax.swing.JTextField postYearTxt;
    private javax.swing.JTextField sem1TotalTxt;
    private javax.swing.JTextField sem1TotalTxt1;
    private javax.swing.JTextField sem2TotalTxt;
    private javax.swing.JTextField sem2TotalTxt1;
    private javax.swing.JTextField unAddmissionDateTxt;
    private static javax.swing.JTextField unCourseTxt;
    private javax.swing.JTextField unEmailTxt;
    private javax.swing.JTextField unFacultyTxt;
    private javax.swing.JTextField unNameTxt;
    private javax.swing.JButton unSem1ManageSubjectBtn;
    private static javax.swing.JPanel unSem1SubjectPanel;
    private javax.swing.JButton unSem2ManageSubjectBtn;
    private static javax.swing.JPanel unSem2SubjectPanel;
    private javax.swing.JTextField unYearTxt;
    private static javax.swing.JComboBox<String> underGadmissionNoCombo;
    private javax.swing.JButton underGraSaveBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * load under graduates admission no to combo
     */
    private void fillUnderGraduatesAdmissionNoCombo(){
        try {
            ArrayList<UnderGraduateStudent> underGraduateStudents=UnderGraduateStudentController.
                    getAllUnderGraduateStudent();
            for (UnderGraduateStudent underGraduateStudent : underGraduateStudents) {
                underGadmissionNoCombo.addItem(underGraduateStudent.getAddmissionNo());
            }
            new ComboSearch().setSearchableCombo(underGadmissionNoCombo, true, "No UnderGraduateStudent found");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * load post graduates admission no to combo
     */
    private void fillPostGraduatesAdmissionNoCombo(){
        try {
            ArrayList<PostGraduateStudent> postGraduateStudents=PostGraduateStudentController.getAllPostGraduateStudent();
            for (PostGraduateStudent postGraduateStudent : postGraduateStudents) {
                postGadmissionNoCombo.addItem(postGraduateStudent.getAddmissionNo());
            }
            new ComboSearch().setSearchableCombo(postGadmissionNoCombo, true, "No PostGraduateStudent found");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * load under graduates subjects
     */
    private static void loadUnderGraduteSubjects(){
        try {
            unAdmissionNo = underGadmissionNoCombo.getSelectedItem().toString();
            ArrayList<GetBscSubjects> bscSem1Subjects=BscSubjectController.getStudentAllBscSubject(unAdmissionNo,1);
            ArrayList<GetBscSubjects> bscSem2Subjects=BscSubjectController.getStudentAllBscSubject(unAdmissionNo,2);
            unSem1SubjectPanel.removeAll();
            unSem2SubjectPanel.removeAll();
            loadCompulsarrySubjects();
            if (bscSem1Subjects!=null) {
                for (GetBscSubjects bscSubject : bscSem1Subjects) {
                    Subject subject=SubjectController.searchSubjectId(bscSubject.getSubjectCode());
                    if (!subject.isCompulsary()) {
                        unSem1SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                        if (!unSem1SubjectCodes.contains(subject.getSubjectCode())) {
                            unSem1SubjectCodes.add(subject.getSubjectCode());
                        }
                    }
                }
            }
            if (bscSem2Subjects!=null) {
                for (GetBscSubjects bscSubject : bscSem2Subjects) {
                    Subject subject=SubjectController.searchSubjectId(bscSubject.getSubjectCode());
                    
                    if (!subject.isCompulsary()) {
                        unSem2SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                        if (!unSem2SubjectCodes.contains(subject.getSubjectCode())) {
                            unSem2SubjectCodes.add(subject.getSubjectCode());
                        }
                    }
                }
            }  
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * load post graduates subjects
     */
    private static void loadPostGraduteSubjects(){
        try {
            postAdmissionNo = postGadmissionNoCombo.getSelectedItem().toString();
            ArrayList<GetMscSubjects> mscSem1Subjects=MscSubjectController.getStudentAllMscSubject(postAdmissionNo,1);
            ArrayList<GetMscSubjects> mscSem2Subjects=MscSubjectController.getStudentAllMscSubject(postAdmissionNo,2);
            postSem1SubjectPanel.removeAll();
            postSem2SubjectPanel.removeAll();
            loadCompulsarrySubjects();
            if (mscSem1Subjects!=null) {
                for (GetMscSubjects bscSubject : mscSem1Subjects) {
                    Subject subject=SubjectController.searchSubjectId(bscSubject.getSubjectCode());
                    if (subject.isCompulsary()) {
                        postSem1SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                        if (!psSem1SubjectCodes.contains(subject.getSubjectCode())) {
                            psSem1SubjectCodes.add(subject.getSubjectCode());
                        }
                    }
                }
            }
            if (mscSem2Subjects!=null) {
                for (GetMscSubjects mscSubject : mscSem2Subjects) {
                    Subject subject=SubjectController.searchSubjectId(mscSubject.getSubjectCode());
                    if (subject.isCompulsary()) {
                        postSem2SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                        if (!psSem2SubjectCodes.contains(subject.getSubjectCode())) {
                            psSem2SubjectCodes.add(subject.getSubjectCode());
                        }
                    }
                }
            }  
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * 
     * @param bscSubjects
     * @param paymentId 
     */
    public static void upadeBscSubjects(ArrayList<String> bscSubjects,String paymentId){
        try {
            unAdmissionNo=underGadmissionNoCombo.getSelectedItem().toString();
            ArrayList<String> bscSubjectList=bscSubjects;
            for (String subjectCode : bscSubjectList) {
                BscSubject bscSubject = new BscSubject(subjectCode, unAdmissionNo, paymentId, 0.00, TimeCalculator.getToDayDate());
                BscSubjectController.addBscSubject(bscSubject);
            }
            loadUnderGraduteSubjects();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * 
     * @param mscSubjects
     * @param paymentId 
     */
    public static void upadeMscSubjects(ArrayList<String> mscSubjects, String paymentId){
        try {
            ArrayList<String> mscSubjectList=mscSubjects;
            for (String subjectCode : mscSubjectList) {
                MscSubjects mscSubject = new MscSubjects(subjectCode, postAdmissionNo, paymentId, 0.00, TimeCalculator.getToDayDate());
                MscSubjectController.addMscSubjects(mscSubject);
            }
            loadPostGraduteSubjects();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * load all compulsory subjects
     */
    private static void loadCompulsarrySubjects(){
        try {
            //String underGraduateStudentId = underGadmissionNoCombo.getSelectedItem().toString();
            String unCourse=UnderGraduateStudentController.searchUnderGraduateStudent(unAdmissionNo).getCourseId();
            ArrayList<Subject> subjectsUn_1=SubjectController.getAllCompulsorySubject(unCourse,1, 1);
            ArrayList<Subject> subjectsUn_2=SubjectController.getAllCompulsorySubject(unCourse,1, 2);
            //String postGraduateStudentId = postGadmissionNoCombo.getSelectedItem().toString();
            System.out.println("unAdmissionNo "+unAdmissionNo);
            System.out.println("postAdmissionNo "+postAdmissionNo);
            ArrayList<Subject> subjectsPo_1=new ArrayList<>();
            ArrayList<Subject> subjectsPo_2=new ArrayList<>();
            if (!postAdmissionNo.equals("")) {
                String poCourse = PostGraduateStudentController.searchPostGraduateStudent(postAdmissionNo).getCourseId();
                subjectsPo_1=SubjectController.getAllCompulsorySubject(poCourse,1, 1);
                subjectsPo_2=SubjectController.getAllCompulsorySubject(poCourse,1, 2);
            }
            
            if (subjectsUn_1!=null) {
                for(Subject subject : subjectsUn_1) {
                    unSem1SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                    if (!unSem1SubjectCodes.contains(subject.getSubjectCode())) {
                        unSem1SubjectCodes.add(subject.getSubjectCode());
                    }
                }
            }
            if (subjectsUn_2!=null) {
                for(Subject subject : subjectsUn_2) {
                    unSem2SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                    if (!unSem2SubjectCodes.contains(subject.getSubjectCode())) {
                        unSem2SubjectCodes.add(subject.getSubjectCode());
                    }
                }
            }
            if (subjectsPo_1!=null) {
                for(Subject subject : subjectsPo_1) {
                    postSem1SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                    psSem1SubjectCodes.add(subject.getSubjectCode());
                }
            }
            if (subjectsPo_2!=null) {
                for(Subject subject : subjectsPo_2) {
                    postSem2SubjectPanel.add(new SubjectNamePanel(subject.getName(), Double.toString(subject.getFee())));
                    psSem2SubjectCodes.add(subject.getSubjectCode());
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
