/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import controller.CourseController;
import controller.FacultyController;
import controller.PostGraduateStudentController;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Course;
import model.Faculty;
import model.PostGraduateStudent;
import other.ComboSearch;
import other.IDGenerator;

/**
 *
 * @author DinukaMedis
 */
public class RegisterPostGraduateStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentPanel
     */
    public RegisterPostGraduateStudentPanel() {
        initComponents();
        fillCourseCombo();
        fillFacultyCombo();
        loadNewId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        picFrame = new javax.swing.JLabel();
        changePicBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        dobTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        phoneNoTxt = new javax.swing.JTextField();
        addmissionDateTxt = new javax.swing.JTextField();
        nicTxt = new javax.swing.JTextField();
        addmissionNoTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        courseCombo = new javax.swing.JComboBox<>();
        facultyCombo = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        yearOfCompletionTxt = new javax.swing.JTextField();
        qualificationTypeTxt = new javax.swing.JTextField();
        instituteTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePics/dpSample.png"))); // NOI18N
        picFrame.setText("jLabel1");
        picFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(picFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 150));

        changePicBtn.setText("Change");
        changePicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePicBtnActionPerformed(evt);
            }
        });
        jPanel1.add(changePicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Course :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Faculty :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Admission No :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("NIC :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Admission Date :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Date of Birthday :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("E mail :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Phone No :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Address :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, 30));

        addressTxt.setColumns(20);
        addressTxt.setRows(5);
        jScrollPane1.setViewportView(addressTxt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 260, 110));

        dobTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(dobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 200, -1));

        emailTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 310, -1));

        genderTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, -1));

        phoneNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(phoneNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 190, -1));

        addmissionDateTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addmissionDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmissionDateTxtActionPerformed(evt);
            }
        });
        jPanel2.add(addmissionDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, -1));

        nicTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, -1));

        addmissionNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addmissionNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmissionNoTxtActionPerformed(evt);
            }
        });
        jPanel2.add(addmissionNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 170, -1));

        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 310, -1));

        courseCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courseCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseComboItemStateChanged(evt);
            }
        });
        jPanel2.add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 260, -1));

        facultyCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        facultyCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facultyComboItemStateChanged(evt);
            }
        });
        jPanel2.add(facultyCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 260, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 520, 610));

        addBtn.setBackground(new java.awt.Color(51, 255, 255));
        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addBtn.setText("Register");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 390, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Other Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Qualification type :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Year of Complation :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 30));

        yearOfCompletionTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        yearOfCompletionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearOfCompletionTxtKeyReleased(evt);
            }
        });
        jPanel3.add(yearOfCompletionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));

        qualificationTypeTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        qualificationTypeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qualificationTypeTxtKeyReleased(evt);
            }
        });
        jPanel3.add(qualificationTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 190, -1));

        instituteTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        instituteTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                instituteTxtKeyReleased(evt);
            }
        });
        jPanel3.add(instituteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 190, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("Institute :");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 390, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addmissionDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmissionDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmissionDateTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            String addmissionNo=addmissionNoTxt.getText();
            String addmissionDate=addmissionDateTxt.getText();
            String name=nameTxt.getText();
            String nic=nicTxt.getText();
            String dob=dobTxt.getText();
            String gender=genderTxt.getText();
            String email=emailTxt.getText();
            String address=addressTxt.getText();
            int phoneNo=Integer.parseInt(phoneNoTxt.getText());
            String qualificationType=qualificationTypeTxt.getText();
            int yearOfCompletion=Integer.parseInt(yearOfCompletionTxt.getText());
            String institute=instituteTxt.getText();
            String facultyId=FacultyController.searchFacultyName(facultyCombo.getSelectedItem().toString()).getFacultyId();
            String courseId=CourseController.searchCourseName(courseCombo.getSelectedItem().toString()).getCourseId();
            String labId="";
            int totalCredites=0;
            
            PostGraduateStudent postGraduateStudent=new PostGraduateStudent(addmissionNo, addmissionDate, name, nic, dob, gender, email, address, phoneNo,qualificationType, yearOfCompletion, institute, facultyId, courseId, labId, totalCredites);            
            int isAdded=PostGraduateStudentController.addPostGraduateStudent(postGraduateStudent);
            if (isAdded>0) {
                JOptionPane.showMessageDialog(this, "Student Added successfully....");
            }else{
                JOptionPane.showMessageDialog(this, "Somthing wrong....");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void courseComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseComboItemStateChanged
        
    }//GEN-LAST:event_courseComboItemStateChanged

    private void addmissionNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmissionNoTxtActionPerformed
        
    }//GEN-LAST:event_addmissionNoTxtActionPerformed

    private void yearOfCompletionTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearOfCompletionTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_yearOfCompletionTxtKeyReleased

    private void qualificationTypeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qualificationTypeTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationTypeTxtKeyReleased

    private void instituteTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instituteTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_instituteTxtKeyReleased

    private void facultyComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facultyComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyComboItemStateChanged

    private void changePicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePicBtnActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Save Image");
            chooser.setFileFilter(new FileNameExtensionFilter("IMAGES ONLY", "png", "jpeg", "jpg")); //this file extentions are shown
            BufferedImage image=new BufferedImage(110, 150, BufferedImage.TRANSLUCENT);
            int showSaveDialog = chooser.showSaveDialog(this);
            String filePath = "G:\\UCSC\\2nd year\\2year1sem\\SCS2104_Programming III\\"
                    + "JAVA take home\\NewProject\\TakeHomeAssignment_New\\src\\images\\profilePics";//chooser.getCurrentDirectory().toString().replace("\\", "/");
            String fileName = chooser.getSelectedFile().getName(); //get user entered file name to save
            ImageIO.write(image, "PNG", new File(filePath + "/" + fileName + ".png"));
        } catch (IOException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changePicBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addmissionDateTxt;
    private javax.swing.JTextField addmissionNoTxt;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JButton changePicBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JComboBox<String> facultyCombo;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JTextField instituteTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JTextField phoneNoTxt;
    private javax.swing.JLabel picFrame;
    private javax.swing.JTextField qualificationTypeTxt;
    private javax.swing.JTextField yearOfCompletionTxt;
    // End of variables declaration//GEN-END:variables

    private void fillCourseCombo(){
        try {
            ArrayList<Course> courses=CourseController.getAllCourse();
            for (Course course : courses) {
                courseCombo.addItem(course.getName());
            }
            new ComboSearch().setSearchableCombo(courseCombo, true, "No Course found");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegisterPostGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    private void fillFacultyCombo(){
        try {
            ArrayList<Faculty> faculties=FacultyController.getAllFaculty();
            for (Faculty faculty : faculties) {
                facultyCombo.addItem(faculty.getName());
            }
            new ComboSearch().setSearchableCombo(facultyCombo, true, "No Faculty found");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegisterPostGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    private void loadNewId(){
        try {
            String newId = IDGenerator.getNewId("postgraduateStudent", "admissionNo", "po");
            addmissionNoTxt.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
