/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import controller.CourseController;
import controller.UnderGraduateStudentController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Course;
import model.UnderGraduateStudent;
import other.ComboSearch;

/**
 *
 * @author DinukaMedis
 */
public class SearchUnderGraduateStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentPanel
     */
    public SearchUnderGraduateStudentPanel() {
        initComponents();
        fillCourseCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        resultsBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        dobTxt = new javax.swing.JTextField();
        facultyTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        phoneNoTxt = new javax.swing.JTextField();
        nicTxt = new javax.swing.JTextField();
        addmissionNoTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        courseCombo = new javax.swing.JComboBox<>();
        addmissionDateTxt = new javax.swing.JPasswordField();
        searchBtn = new javax.swing.JButton();
        picFrame = new javax.swing.JLabel();
        changePicBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        facultyTxt1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        sub4Txt = new javax.swing.JTextField();
        sub3Txt = new javax.swing.JTextField();
        sub2Txt = new javax.swing.JTextField();
        sub1Txt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        sub4Txt1 = new javax.swing.JTextField();
        sub3Txt1 = new javax.swing.JTextField();
        sub2Txt1 = new javax.swing.JTextField();
        sub1Txt1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rankTxt1 = new javax.swing.JTextField();
        districtCombo1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        sub4Txt2 = new javax.swing.JTextField();
        sub3Txt2 = new javax.swing.JTextField();
        sub2Txt2 = new javax.swing.JTextField();
        sub1Txt2 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteBtn.setBackground(new java.awt.Color(51, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 190, 30));

        resultsBtn.setBackground(new java.awt.Color(51, 255, 255));
        resultsBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resultsBtn.setText("RESULTS");
        jPanel1.add(resultsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 180, 30));

        updateBtn.setBackground(new java.awt.Color(51, 255, 255));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 190, 30));

        addBtn.setBackground(new java.awt.Color(51, 255, 255));
        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 190, 30));

        paymentBtn.setBackground(new java.awt.Color(51, 255, 255));
        paymentBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        paymentBtn.setText("PAYMENTS");
        jPanel1.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 180, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Course :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Faculty :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Admission No :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 130, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("NIC :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Admission Date :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Date of Birthday :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("E mail :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Phone No :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Address :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 30));

        addressTxt.setColumns(20);
        addressTxt.setRows(5);
        jScrollPane1.setViewportView(addressTxt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 260, 90));

        dobTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(dobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 260, -1));

        facultyTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(facultyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 260, -1));

        emailTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 350, -1));

        genderTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, -1));

        phoneNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(phoneNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 200, -1));

        nicTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 170, -1));

        addmissionNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addmissionNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmissionNoTxtActionPerformed(evt);
            }
        });
        jPanel2.add(addmissionNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 170, -1));

        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 310, -1));

        courseCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courseCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseComboItemStateChanged(evt);
            }
        });
        jPanel2.add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 260, -1));

        addmissionDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmissionDateTxtActionPerformed(evt);
            }
        });
        addmissionDateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addmissionDateTxtKeyReleased(evt);
            }
        });
        jPanel2.add(addmissionDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 30));

        searchBtn.setBackground(new java.awt.Color(51, 255, 255));
        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        picFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePics/dpSample.png"))); // NOI18N
        picFrame.setText("jLabel1");
        picFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(picFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 150));

        changePicBtn.setText("Change");
        jPanel2.add(changePicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Select for 4th Year :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 170, 30));

        facultyTxt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(facultyTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 260, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 610));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub4Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub4Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub4TxtKeyReleased(evt);
            }
        });
        jPanel3.add(sub4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        sub3Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub3Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub3TxtKeyReleased(evt);
            }
        });
        jPanel3.add(sub3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, -1));

        sub2Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub2Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub2TxtKeyReleased(evt);
            }
        });
        jPanel3.add(sub2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        sub1Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub1TxtKeyReleased(evt);
            }
        });
        jPanel3.add(sub1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 420, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "A/L Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub4Txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub4Txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub4Txt1KeyReleased(evt);
            }
        });
        jPanel4.add(sub4Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        sub3Txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub3Txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub3Txt1KeyReleased(evt);
            }
        });
        jPanel4.add(sub3Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, -1));

        sub2Txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub2Txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub2Txt1KeyReleased(evt);
            }
        });
        jPanel4.add(sub2Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        sub1Txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub1Txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub1Txt1KeyReleased(evt);
            }
        });
        jPanel4.add(sub1Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("Rank :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, 30));

        rankTxt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rankTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankTxt1ActionPerformed(evt);
            }
        });
        rankTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rankTxt1KeyReleased(evt);
            }
        });
        jPanel4.add(rankTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 110, -1));

        districtCombo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        districtCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                districtCombo1ItemStateChanged(evt);
            }
        });
        jPanel4.add(districtCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 420, 160));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub4Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub4Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub4Txt2KeyReleased(evt);
            }
        });
        jPanel5.add(sub4Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        sub3Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub3Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub3Txt2KeyReleased(evt);
            }
        });
        jPanel5.add(sub3Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, -1));

        sub2Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub2Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub2Txt2KeyReleased(evt);
            }
        });
        jPanel5.add(sub2Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        sub1Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub1Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub1Txt2KeyReleased(evt);
            }
        });
        jPanel5.add(sub1Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 420, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            String addmissionNo=addmissionNoTxt.getText();
            int isDeleted=UnderGraduateStudentController.deleteUnderGraduateStudent(addmissionNo);
            if (isDeleted>0) {
                JOptionPane.showMessageDialog(this, "Student Deleted successfully....");
            }else{
                JOptionPane.showMessageDialog(this, "Somthing wrong....");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
//        try {
//            String addmissionNo=addmissionNoTxt.getText();
//            String addmissionDate=addmissionDateTxt.getText();
//            String name=nameTxt.getText();
//            String nic=nicTxt.getText();
//            String dob=dobTxt.getText();
//            String gender=genderTxt.getText();
//            String email=emailTxt.getText();
//            String address=addressTxt.getText();
//            int phoneNo=Integer.parseInt(phoneNoTxt.getText());
//            String password=passwordTxt.getText();
//            String facultyId=facultyTxt.getText();
//            String courseId=CourseController.searchCourseName(courseCombo.getSelectedItem().toString()).getCourseId();
//            
//            UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent(addmissionNo, addmissionDate,name, nic, dob, gender, email, address, phoneNo, password, alSub1, alSub2, alSub3,alRank, facultyId, courseId,"",false,0);
//            //UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent("un0002 ", "2018-05-22 ", "dinuka kasun ", "952641514v ", "2018-05-22 ", "M", "dinuka.kasunds@gmail.com ", "73 dampe ",0717275722, "1234 ","a", "a", "a",1, "f0001 ", "c0001 ");
//            int isAdded=UnderGraduateStudentController.addUnderGraduateStudent(underGraduateStudent);
//            if (isAdded>0) {
//                JOptionPane.showMessageDialog(this, "Student Added successfully....");
//            }else{
//                JOptionPane.showMessageDialog(this, "Somthing wrong....");
//            }
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
//        try {
//            String addmissionNo=addmissionNoTxt.getText();
//            String addmissionDate=addmissionDateTxt.getText();
//            String name=nameTxt.getText();
//            String nic=nicTxt.getText();
//            String dob=dobTxt.getText();
//            String gender=genderTxt.getText();
//            String email=emailTxt.getText();
//            String address=addressTxt.getText();
//            int phoneNo=Integer.parseInt(phoneNoTxt.getText());
//            String password=passwordTxt.getText();
//            String facultyId=facultyTxt.getText();
//            String courseId=CourseController.searchCourseName(courseCombo.getSelectedItem().toString()).getCourseId();
//            
//            UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent(addmissionNo, addmissionDate,name, nic, dob, gender, email, address, phoneNo, password, alSub1, alSub2, alSub3,alRank, facultyId, courseId,"",false,0);
//            //UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent("un0002 ", "2018-05-22 ", "dinuka kasun ", "952641514v ", "2018-05-22 ", "M", "dinuka.kasunds@gmail.com ", "73 dampe ",0717275722, "1234 ","a", "a", "a",1, "f0001 ", "c0001 ");
//            int isAdded=UnderGraduateStudentController.updateUnderGraduateStudent(underGraduateStudent);
//            if (isAdded>0) {
//                JOptionPane.showMessageDialog(this, "Student Updated successfully....");
//            }else{
//                JOptionPane.showMessageDialog(this, "Somthing wrong....");
//            }
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addmissionNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmissionNoTxtActionPerformed

    }//GEN-LAST:event_addmissionNoTxtActionPerformed

    private void courseComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseComboItemStateChanged

    }//GEN-LAST:event_courseComboItemStateChanged

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            String addmissionNo=addmissionNoTxt.getText();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.searchUnderGraduateStudent(addmissionNo);
            if (underGraduateStudent!=null) {
                addmissionDateTxt.setText(underGraduateStudent.getAddmissionDate());
                nameTxt.setText(underGraduateStudent.getName());
                nicTxt.setText(underGraduateStudent.getNic());
                dobTxt.setText(underGraduateStudent.getDob());
                genderTxt.setText(underGraduateStudent.getGender());
                emailTxt.setText(underGraduateStudent.getEmail());
                addressTxt.setText(underGraduateStudent.getAddress());
                phoneNoTxt.setText(Integer.toString(underGraduateStudent.getPhoneNo()));
                facultyTxt.setText(underGraduateStudent.getFacultyId());
                courseCombo.setSelectedItem(underGraduateStudent.getCourseId());
                String path="/images/profilePics/"+addmissionNo+".png";
                picFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
            }else{
                JOptionPane.showMessageDialog(this, "Student not found..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void sub4TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4TxtKeyReleased

    private void sub3TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3TxtKeyReleased

    private void sub2TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2TxtKeyReleased

    private void sub1TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1TxtKeyReleased

    private void sub4Txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4Txt1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4Txt1KeyReleased

    private void sub3Txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3Txt1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3Txt1KeyReleased

    private void sub2Txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2Txt1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2Txt1KeyReleased

    private void sub1Txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1Txt1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1Txt1KeyReleased

    private void rankTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankTxt1ActionPerformed

    private void rankTxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rankTxt1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rankTxt1KeyReleased

    private void districtCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_districtCombo1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_districtCombo1ItemStateChanged

    private void sub4Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4Txt2KeyReleased

    private void sub3Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3Txt2KeyReleased

    private void sub2Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2Txt2KeyReleased

    private void sub1Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1Txt2KeyReleased

    private void addmissionDateTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmissionDateTxtKeyReleased
       
    }//GEN-LAST:event_addmissionDateTxtKeyReleased

    private void addmissionDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmissionDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmissionDateTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPasswordField addmissionDateTxt;
    private javax.swing.JTextField addmissionNoTxt;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JButton changePicBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> districtCombo1;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField facultyTxt;
    private javax.swing.JTextField facultyTxt1;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JTextField phoneNoTxt;
    private javax.swing.JLabel picFrame;
    private javax.swing.JTextField rankTxt1;
    private javax.swing.JButton resultsBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField sub1Txt;
    private javax.swing.JTextField sub1Txt1;
    private javax.swing.JTextField sub1Txt2;
    private javax.swing.JTextField sub2Txt;
    private javax.swing.JTextField sub2Txt1;
    private javax.swing.JTextField sub2Txt2;
    private javax.swing.JTextField sub3Txt;
    private javax.swing.JTextField sub3Txt1;
    private javax.swing.JTextField sub3Txt2;
    private javax.swing.JTextField sub4Txt;
    private javax.swing.JTextField sub4Txt1;
    private javax.swing.JTextField sub4Txt2;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void fillCourseCombo(){
        try {
            ArrayList<Course> courses=CourseController.getAllCourse();
            for (Course course : courses) {
                courseCombo.addItem(course.getName());
            }
            new ComboSearch().setSearchableCombo(courseCombo, true, "No Course found");
            //new ComboSearch().setSearchableCombo(student_idCOmbo, true, "No Student found");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
