/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import controller.CourseController;
import controller.FacultyController;
import controller.PostGraduateStudentController;
import controller.UnderGraduateStudentController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Course;
import model.Faculty;
import model.PostGraduateStudent;
import model.UnderGraduateStudent;
import other.ComboSearch;
import other.IDGenerator;

/**
 *
 * @author DinukaMedis
 */
public class SearchPostGraduateStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentPanel
     */
    public SearchPostGraduateStudentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        deleteBtn1 = new javax.swing.JButton();
        resultsBtn = new javax.swing.JButton();
        updateBtn1 = new javax.swing.JButton();
        addBtn1 = new javax.swing.JButton();
        paymentBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        dobTxt = new javax.swing.JTextField();
        facultyTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        phoneNoTxt = new javax.swing.JTextField();
        addmissionDateTxt = new javax.swing.JTextField();
        nicTxt = new javax.swing.JTextField();
        addmissionNoTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        courseCombo = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        picFrame = new javax.swing.JLabel();
        changePicBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        sub4Txt = new javax.swing.JTextField();
        sub3Txt = new javax.swing.JTextField();
        sub2Txt = new javax.swing.JTextField();
        sub1Txt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        sub4Txt2 = new javax.swing.JTextField();
        sub3Txt2 = new javax.swing.JTextField();
        sub2Txt2 = new javax.swing.JTextField();
        sub1Txt2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        yearOfComplationTxt = new javax.swing.JTextField();
        qualificationTypeTxt = new javax.swing.JTextField();
        instituteTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteBtn1.setBackground(new java.awt.Color(51, 255, 255));
        deleteBtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteBtn1.setText("DELETE");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });
        jPanel4.add(deleteBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 190, 30));

        resultsBtn.setBackground(new java.awt.Color(51, 255, 255));
        resultsBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resultsBtn.setText("RESULTS");
        jPanel4.add(resultsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 180, 30));

        updateBtn1.setBackground(new java.awt.Color(51, 255, 255));
        updateBtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateBtn1.setText("UPDATE");
        updateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn1ActionPerformed(evt);
            }
        });
        jPanel4.add(updateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 190, 30));

        addBtn1.setBackground(new java.awt.Color(51, 255, 255));
        addBtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addBtn1.setText("ADD");
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });
        jPanel4.add(addBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 190, 30));

        paymentBtn1.setBackground(new java.awt.Color(51, 255, 255));
        paymentBtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        paymentBtn1.setText("PAYMENTS");
        jPanel4.add(paymentBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 180, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Course :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Faculty :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Admission No :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 130, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("NIC :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Admission Date :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Date of Birthday :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("E mail :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Phone No :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Address :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 30));

        addressTxt.setColumns(20);
        addressTxt.setRows(5);
        jScrollPane1.setViewportView(addressTxt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 270, 90));

        dobTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(dobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 270, -1));

        facultyTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(facultyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 270, -1));

        emailTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 320, -1));

        genderTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 120, -1));

        phoneNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(phoneNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 170, -1));

        addmissionDateTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addmissionDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmissionDateTxtActionPerformed(evt);
            }
        });
        jPanel2.add(addmissionDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 270, -1));

        nicTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 170, -1));

        addmissionNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addmissionNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmissionNoTxtActionPerformed(evt);
            }
        });
        jPanel2.add(addmissionNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 170, -1));

        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 270, -1));

        courseCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courseCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseComboItemStateChanged(evt);
            }
        });
        jPanel2.add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 270, -1));

        searchBtn.setBackground(new java.awt.Color(51, 255, 255));
        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 90, -1));

        picFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePics/dpSample.png"))); // NOI18N
        picFrame.setText("jLabel1");
        picFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(picFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 150));

        changePicBtn.setText("Change");
        jPanel2.add(changePicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 610));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub4Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub4Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub4TxtKeyReleased(evt);
            }
        });
        jPanel5.add(sub4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        sub3Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub3Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub3TxtKeyReleased(evt);
            }
        });
        jPanel5.add(sub3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, -1));

        sub2Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub2Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub2TxtKeyReleased(evt);
            }
        });
        jPanel5.add(sub2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        sub1Txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub1TxtKeyReleased(evt);
            }
        });
        jPanel5.add(sub1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 410, 110));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Semester 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub4Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub4Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub4Txt2KeyReleased(evt);
            }
        });
        jPanel7.add(sub4Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        sub3Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub3Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub3Txt2KeyReleased(evt);
            }
        });
        jPanel7.add(sub3Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, -1));

        sub2Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub2Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub2Txt2KeyReleased(evt);
            }
        });
        jPanel7.add(sub2Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        sub1Txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sub1Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sub1Txt2KeyReleased(evt);
            }
        });
        jPanel7.add(sub1Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 410, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Other Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Qualification type :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Year of Complation :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 30));

        yearOfComplationTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        yearOfComplationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearOfComplationTxtKeyReleased(evt);
            }
        });
        jPanel3.add(yearOfComplationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, -1));

        qualificationTypeTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        qualificationTypeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qualificationTypeTxtKeyReleased(evt);
            }
        });
        jPanel3.add(qualificationTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 210, -1));

        instituteTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        instituteTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                instituteTxtKeyReleased(evt);
            }
        });
        jPanel3.add(instituteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("Institute :");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 410, 160));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearOfComplationTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearOfComplationTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_yearOfComplationTxtKeyReleased

    private void qualificationTypeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qualificationTypeTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationTypeTxtKeyReleased

    private void instituteTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instituteTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_instituteTxtKeyReleased

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        try {
            String addmissionNo=addmissionNoTxt.getText();
            int isDeleted=UnderGraduateStudentController.deleteUnderGraduateStudent(addmissionNo);
            if (isDeleted>0) {
                JOptionPane.showMessageDialog(this, "Student Deleted successfully....");
            }else{
                JOptionPane.showMessageDialog(this, "Somthing wrong....");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void updateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn1ActionPerformed
//        try {
//            String addmissionNo=addmissionNoTxt.getText();
//            String addmissionDate=addmissionDateTxt.getText();
//            String name=nameTxt.getText();
//            String nic=nicTxt.getText();
//            String dob=dobTxt.getText();
//            String gender=genderTxt.getText();
//            String email=emailTxt.getText();
//            String address=addressTxt.getText();
//            int phoneNo=Integer.parseInt(phoneNoTxt.getText());
//            String password=passwordTxt.getText();
//            String facultyId=facultyTxt.getText();
//            String courseId=CourseController.searchCourseName(courseCombo.getSelectedItem().toString()).getCourseId();
//
//            UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent(addmissionNo, addmissionDate,name, nic, dob, gender, email, address, phoneNo, password, alSub1, alSub2, alSub3,alRank, facultyId, courseId,"",false,0);
//            //UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent("un0002 ", "2018-05-22 ", "dinuka kasun ", "952641514v ", "2018-05-22 ", "M", "dinuka.kasunds@gmail.com ", "73 dampe ",0717275722, "1234 ","a", "a", "a",1, "f0001 ", "c0001 ");
//            int isAdded=UnderGraduateStudentController.updateUnderGraduateStudent(underGraduateStudent);
//            if (isAdded>0) {
//                JOptionPane.showMessageDialog(this, "Student Updated successfully....");
//            }else{
//                JOptionPane.showMessageDialog(this, "Somthing wrong....");
//            }
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_updateBtn1ActionPerformed

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
//        try {
//            String addmissionNo=addmissionNoTxt.getText();
//            String addmissionDate=addmissionDateTxt.getText();
//            String name=nameTxt.getText();
//            String nic=nicTxt.getText();
//            String dob=dobTxt.getText();
//            String gender=genderTxt.getText();
//            String email=emailTxt.getText();
//            String address=addressTxt.getText();
//            int phoneNo=Integer.parseInt(phoneNoTxt.getText());
//            String password=passwordTxt.getText();
//            String facultyId=facultyTxt.getText();
//            String courseId=CourseController.searchCourseName(courseCombo.getSelectedItem().toString()).getCourseId();
//
//            UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent(addmissionNo, addmissionDate,name, nic, dob, gender, email, address, phoneNo, password, alSub1, alSub2, alSub3,alRank, facultyId, courseId,"",false,0);
//            //UnderGraduateStudent underGraduateStudent=new UnderGraduateStudent("un0002 ", "2018-05-22 ", "dinuka kasun ", "952641514v ", "2018-05-22 ", "M", "dinuka.kasunds@gmail.com ", "73 dampe ",0717275722, "1234 ","a", "a", "a",1, "f0001 ", "c0001 ");
//            int isAdded=UnderGraduateStudentController.addUnderGraduateStudent(underGraduateStudent);
//            if (isAdded>0) {
//                JOptionPane.showMessageDialog(this, "Student Added successfully....");
//            }else{
//                JOptionPane.showMessageDialog(this, "Somthing wrong....");
//            }
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(SearchUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void addmissionDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmissionDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmissionDateTxtActionPerformed

    private void addmissionNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmissionNoTxtActionPerformed

    }//GEN-LAST:event_addmissionNoTxtActionPerformed

    private void courseComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseComboItemStateChanged

    }//GEN-LAST:event_courseComboItemStateChanged

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            String addmissionNo=addmissionNoTxt.getText();
            UnderGraduateStudent underGraduateStudent=UnderGraduateStudentController.searchUnderGraduateStudent(addmissionNo);
            if (underGraduateStudent!=null) {
                addmissionDateTxt.setText(underGraduateStudent.getAddmissionDate());
                nameTxt.setText(underGraduateStudent.getName());
                nicTxt.setText(underGraduateStudent.getNic());
                dobTxt.setText(underGraduateStudent.getDob());
                genderTxt.setText(underGraduateStudent.getGender());
                emailTxt.setText(underGraduateStudent.getEmail());
                addressTxt.setText(underGraduateStudent.getAddress());
                phoneNoTxt.setText(Integer.toString(underGraduateStudent.getPhoneNo()));
                facultyTxt.setText(underGraduateStudent.getFacultyId());
                courseCombo.setSelectedItem(underGraduateStudent.getCourseId());
                String path="/images/profilePics/"+addmissionNo+".png";
                picFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
            }else{
                JOptionPane.showMessageDialog(this, "Student not found..");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterUnderGraduateStudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void sub4TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4TxtKeyReleased

    private void sub3TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3TxtKeyReleased

    private void sub2TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2TxtKeyReleased

    private void sub1TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1TxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1TxtKeyReleased

    private void sub4Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4Txt2KeyReleased

    private void sub3Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3Txt2KeyReleased

    private void sub2Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2Txt2KeyReleased

    private void sub1Txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1Txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1Txt2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn1;
    private javax.swing.JTextField addmissionDateTxt;
    private javax.swing.JTextField addmissionNoTxt;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JButton changePicBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField facultyTxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JTextField instituteTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JButton paymentBtn1;
    private javax.swing.JTextField phoneNoTxt;
    private javax.swing.JLabel picFrame;
    private javax.swing.JTextField qualificationTypeTxt;
    private javax.swing.JButton resultsBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField sub1Txt;
    private javax.swing.JTextField sub1Txt2;
    private javax.swing.JTextField sub2Txt;
    private javax.swing.JTextField sub2Txt2;
    private javax.swing.JTextField sub3Txt;
    private javax.swing.JTextField sub3Txt2;
    private javax.swing.JTextField sub4Txt;
    private javax.swing.JTextField sub4Txt2;
    private javax.swing.JButton updateBtn1;
    private javax.swing.JTextField yearOfComplationTxt;
    // End of variables declaration//GEN-END:variables

    
}
