/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

/**
 *
 * @author DinukaMedis
 */
public class SubjectNamePanel extends javax.swing.JPanel {

    /**
     * Creates new form SubjectNamePanel
     * @param subjectName
     * @param price
     */
    public SubjectNamePanel(String subjectName, String price) {
        initComponents();
        subjectNameTxt.setText(subjectName);
        priceTxt.setText("Rs:"+price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subjectNameTxt = new javax.swing.JLabel();
        priceTxt = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subjectNameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        subjectNameTxt.setText("Subject Name ");
        jPanel1.add(subjectNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 30));

        priceTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        priceTxt.setText("Rs:2000.00");
        jPanel1.add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceTxt;
    private javax.swing.JLabel subjectNameTxt;
    // End of variables declaration//GEN-END:variables
}
